# -*- coding: utf-8 -*-
"""svc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GOHfHM8RpE9Ke1AaHwD7YUD6JwrG3Nor
"""

import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer , TfidfVectorizer
from sklearn.preprocessing import StandardScaler

from sklearn import svm
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report

from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split, cross_val_score

filename = r''
names = ['preg','plas','pres','skin','test','mass','pedi','age','class']
dataframe = pd.read_csv(filename, names=names)
array = dataframe.values
X = array[:,0:8]
Y = array[:,8]

X_train, X_test, y_train, y_test = train_test_split(X , Y , test_size = 0.3)

from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

svc = SVC()

parm_grid = {
    'C' : [0.1,1,10,10],
    'gamma' : [0.01, 1, 10]
    'kernel' : ['linear','rbf']
    }

grid_search = GridSearchCV(estimator=svc, param_grid=parm_grid, cv=5)
grid_search.fit(X_train, y_train)

print("Best parameters :", grid_search.best_params_)
print("Best cross-validation score:", grid_search.best_score_)