# -*- coding: utf-8 -*-
"""xgbm

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17dA2BnWgrJE2DBsAKFB_ARPlYLvn5SeY
"""



from numpy import loadtxt
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

from google.colab import drive
drive.mount('/content/drive')

dataset=loadtxt('/content/drive/MyDrive/pima-indians-diabetes.data.csv',delimiter=",")
X=dataset[:,0:8]
Y=dataset[:,8]

seed = 7
test_size = 0.33
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

model = XGBClassifier()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
predictions = [round(value) for value in y_pred]

accuracy = accuracy_score(y_test, predictions)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

predictions

import numpy as np
impoet